### ISSUE TITLE
ÆØÅ fremvises ikke korrekt på staff-listen

### ISSUE THREAD

**Issue by rasm945i** [SaimorIVS/Stavox-Issues#14]
**Beskriv problemet**
ÆØÅ ser ikke ud til at fungere korrekt på staff-listen https://stavox.dk/dash/stafflist
Jeg tjekkede HTML source, UTF-8 er sat til, så jeg mistænker at det kan være gammel data i databasen som ikke er blevet opdateret.

**For at reproducere fejlen**
Skridt for at støde ind i fejlen:
1. Gå til https://stavox.dk/dash/stafflist
2. Kig på linjerne hvor der burde stå "Håndtering", men der står "HÃ¥ndtering"

**Screenshots**
![2022-02-28 23_59_57-Stavox - Staffliste – Google Chrome](https://user-images.githubusercontent.com/30770655/156072645-bfec3992-de20-4d28-bf45-d202f1d9284e.png)

**Andet**
Intet.

**Comment by MStruntze** [comment]
Fixed
