### ISSUE TITLE
"Forumprofil"-knap virker ikke

### ISSUE THREAD

**Issue by rasm945i** [SaimorIVS/Stavox-Issues#15]
**Beskriv problemet**
"Forumprofil" knappen virker ikke ikke, men efter at inspicere elementet ligner det at i er klar over det, men på siden ligner det et design-valg at knappen skal være rød, da alle er det.

**For at reproducere fejlen**
Skridt for at støde ind i fejlen:
1. Gå til https://stavox.dk/dash/stafflist
2. Undrer dig over hvorfor de fremhævede "Forumprofil" knapper ikke virker.

**Screenshots**
![2022-02-28 23_59_57-Stavox - Staffliste – Google Chrome](https://user-images.githubusercontent.com/30770655/156072645-bfec3992-de20-4d28-bf45-d202f1d9284e.png)

**Andet**
Intet.

**Comment by MStruntze** [comment]
Fixed
