### ISSUE TITLE
[Uber] Mister penge af at stoppe som Uber

### ISSUE THREAD

**Issue by BareMaxx** [SaimorIVS/Stavox-Issues#26]
**Beskriv problemet**
Hvis man stopper som Uber, mens der er en bestilling (som man IKKE har accepteret), så mister man de penge som man registrede sine ture til at koste, selvom man ikke har modtaget nogen.

**For at reproducere fejlen**
Skridt for at støde ind i fejlen:
1. Bliv Uber
2. Modtag en ordre
3. Stop som Uber

**Comment by MStruntze** [comment]
Der har været et "gebyr" for at stoppe som chauffør svarende til tur-prisen. Den er nu fjernet. Det var uafhængigt af, om man havde en afventende tur.
