### ISSUE TITLE
[Uber] Følgende destinationer kan ikke bruges

### ISSUE THREAD

**Issue by meow-0** [SaimorIVS/Stavox-Issues#28]
Alle nedenstående destinationer kan ikke bruges da de ikke har postkasser:
Mesalejlighed #1-#12
Lejlighed #1-#6
Industribygning #1-#2
Butik 10
Jobbil
Politibil

Og så er der den her? 
![image](https://user-images.githubusercontent.com/67144339/195670386-43ab82f1-bdfb-46c0-b9ab-5e726ba08953.png)

**Comment by Dumspy** [comment]
Dupe of closed issue #24
