### ISSUE TITLE
Weld/Adv dupe 2 bugger

### ISSUE THREAD

**Issue by LollyDK1** [SaimorIVS/Stavox-Issues#36]
**Beskrivelse:**
Jeg har nu 2 gange bygget på en base, brugt weld alt knappen og dupet min bygning, når jeg så prøver og spawne den igen så mangler store dele af bygningnen.

**For at reproducere fejlen**
Skridt for at støde ind i fejlen:
1. Byg noget ud af flere props 15+
2. Weld alt og dupe den
3. Spawn den igen

**Andet**
Det er meget muligt mig der er idiot, men tviler.

**Comment by aske02** [comment]
Det virker ikke til at det er muligt at gentage fejlen, kan du lave en mere detaljeret gennemgang af hvordan man skal gøre eller vise noget video med fejlen i.

**Comment by Dumspy** [comment]
Vi har ikke kunnne reproducere fejlen hvis du kan optage ller udbyde hvad du gør for at få det til at ske så opret et nyt issue med det
