### ISSUE TITLE
"Fjern" proppen bag i GMC trucken

### ISSUE THREAD

**Issue by meow-0** [SaimorIVS/Stavox-Issues#4]
Ved at bruge modshoppen eller de gamle plader, og simpelthen bare køre ud af cardealer området, vil rulledøren på GMC trucken være nede, men den vil ikke have spawnet nogen prop. Hvis man åbner og lukker porten, fjerner den proppen, men ikke rulledøren. Dette kunne jeg ikke få til at virke i min video, da det er lidt mere sjældent. 

https://youtu.be/ztvdMDZXBwI

**Comment by MStruntze** [comment]
Fixed
