### ISSUE TITLE
NPC'erne har stadig spoooky tilbehør på

### ISSUE THREAD

**Issue by meow-0** [SaimorIVS/Stavox-Issues#40]

**Comment by meow-0** [comment]
![image](https://user-images.githubusercontent.com/67144339/200169883-1725ff91-18a5-4442-9e4a-5323de4b8524.png)

**Comment by aske02** [comment]
Masken til venstre blev aldrig brugt til NPC'er. Er du sikker på det ikke er en spillers props?
