### ISSUE TITLE
Forbedre script som bestemmer hvornår biler må respawnes.

### ISSUE THREAD

**Issue by Rapps21** [SaimorIVS/Stavox-Issues#41]
**landmanden kunne sætte sin bil i garagen, selvom vi næsten lige havde kørt rundt i den**

Nogen havde stjålet hans bil fra konfiskerings-pladsen, og så havde vi parkeret den tilbage igen, hvor at 8 minutter efter kunne han respawne den

**Comment by aske02** [comment]
Bilers respawn time er baseret på hvornår ejeren sidst kørte i den.
