### ISSUE TITLE
Våben stacker ikke

### ISSUE THREAD

**Issue by LollyDK1** [SaimorIVS/Stavox-Issues#53]
**Beskriv problemet**
2 P2000 blev ikke stacket i mit inventory, heller ikke i bagagerummet på den bil jeg fik dem fra.

**For at reproducere fejlen**
Skridt for at støde ind i fejlen:
Fandt dem i en bil der blev fjernet pga at en person leavede.

**Screenshots**
![image](https://user-images.githubusercontent.com/117306429/212496918-d1bcba31-7507-4c63-9aba-0b8b2d8db9f9.png)

**Andet**
Jeg kan godt lide kage.

**Comment by aske02** [comment]
Can't reproduce
