### ISSUE TITLE
Fotovogne stander virker ved sprunget fotovogn

### ISSUE THREAD

**Issue by Falkefly** [SaimorIVS/Stavox-Issues#59]
**Fotovogne stander virker ved sprunget fotovogn**
Når du springer en fotovogn (ATK) virker fartmåleren stadig

**For at reproducere fejlen**
Skridt for at støde ind i fejlen:
1. Gå til spring i fotovogn i luften mens standeren er ued
2. Klik på standeren vil stadig virke selvom fotovognen er sprunget i luften

**Comment by aske02** [comment]
Det er bevidst at fotovognens kamera ikke stopper når man springer den.
