### ISSUE TITLE
Ikke VIP printere æder opgraderingskort.

### ISSUE THREAD

**Issue by meow-0** [SaimorIVS/Stavox-Issues#6]
Hvis man som VIP bruger et opgraderingskort på en ikke-vip printer så æder printeren bare kortet uden at opgradere, eller informere om at den er max level.

Step 1: Vær VIP
Step 2: Anskaf dig en ikke-vip printer
Step 3: Spawn et opgraderingskort
Step 4: Se ikke-vip printeren æde opgraderingskortet.

https://youtu.be/saLCEj1dsWo

**Comment by Mukhle** [comment]
Fixed in SaimorIVS/CABR@da9c368
