### ISSUE TITLE
Trukket ekstra for at lave reklamer for hurtigt fejl.

### ISSUE THREAD

**Issue by BareMaxx** [SaimorIVS/Stavox-Issues#62]
Det er lavet så man bliver trukket ekstra penge for at lave reklamer for ofte (under 3 minutter).
Der går dog 12 minutter mellem mine reklamer, og jeg bliver stadig trukket ekstra.

![image](https://user-images.githubusercontent.com/32611523/229855769-bc9c9608-167b-48d6-9695-e594468eccf7.png)
![image](https://user-images.githubusercontent.com/32611523/229855845-78e2b665-3832-4c25-b310-664ef16a24b9.png)

**Comment by aske02** [comment]
![image of commit](https://i.imgur.com/rCDgGnX.png)
Fixed i dette commit
