### ISSUE TITLE
Konfiskering af ores

### ISSUE THREAD

**Issue by Falkefly** [SaimorIVS/Stavox-Issues#66]
**Beskriv problemet**
Hvis dine våben bliver konfiskeret, mister du også alle ores du har i din inventory, selvom de er lovlige at have, og mining ikke er ulovligt.

**For at reproducere fejlen**
Skridt for at støde ind i fejlen:
1. Køb et våben
2. Mine nogle ores
3. Få konfiskeret dit våben
4. Du mister også dine ores

**Comment by aske02** [comment]
Det er bevidst det fungerer som det gør.
