### ISSUE TITLE
Fartbegrænsnings Bug

### ISSUE THREAD

**Issue by TeNtEdk** [SaimorIVS/Stavox-Issues#67]
Problem:
Man kan komme til at overskride fartgrænsen i byen med sin bil - altså, bypasse den fartbegrænsning der er inde i byen.

Hvordan og hvorledes:
1. En person carjacker din bil som du har ude, imens den bliver carjacket(lockpicket), sætter du den i garagen.
2. Du spawner en anden bil, den bil du spawner, har hverken NOS eller fartbegrænsning inde i byen.

**Comment by aske02** [comment]
Kan ikke genskabe fejlen.
