### ISSUE TITLE
Tablet - "lovlige jobs" og brug af hjemmesider

### ISSUE THREAD

**Issue by meow-0** [SaimorIVS/Stavox-Issues#8]
Som våbenhandler er det tilladt at købe droner, jammer, og oplader. Dog er det ikke tilladt at købe wiretool, og stikdåser, som er nødtventige for at bruge dronestuff.

https://youtu.be/399y2pgO5Es

**Comment by MStruntze** [comment]
Adgang til tablet-sites begrænses på per side basis. Ingen af produkterne kan købes af våbenhandlere.
